INSERT INTO Songs (name, artist)
VALUES
("Clay Pigeons","Michael Cera"),
("The Suburbs", "Arcade Fire"),
("Such Great Heights","The Postal Services"),
("Yes I'm Changing","Tame Impala"),
("Why'd You Only Call Me When You're High","Arctic Monkeys"),
("Pure Comedy","Father John Misty"),
("Leaving LA", "Father John Misty"),
("Burning Down The House","Talking Heads"),
("Fool","Frankie Cosmos"),
("Steady","Strongboys"),
("Nights","Frank Oceans"),
("Maps","Yeah Yeah Yeas"),
("Say It Ain't So","Weezers"),
("Buddy Holly","Weezers"),
("Weekend Woman","Weezers"),
("I Love You So","The Walters"),
("Pleaser","Wallows"),
("Uncomfortable","Wallows"),
("Feels Like We Only Go Backwards","Tame Impala"),
("The Less I Know The Better","Tame Impala");

INSERT INTO Songs (name,artist,album)
VALUES
("Every Single Thing", "HOMESHAKE","Fresh Air");

INSERT INTO Songs (name,artist,album,genre,valence,danceabilty,accessibilty)
VALUES
("It Feels Like We Only Go Backwards","Tame Impala","Lonerism","Neo Psychedelia",3,4,5),
("Let It Happen","Tame Impala","Currents","Neo Psychedelia",4,3,5),
("Yes I'm Changing","Tame Impala","Currents","Neo Psychedelia",2,2,5),
("Past Life","Tame Impala","Currents","Neo Psychedelia",1,2,5),
("List Of People (To Try And Forget About)","Tame Impala",NULL,"Neo Psychedelia",1,2,5),
("Golden Thread","Passenger","Flight of the Crow","Indie Folk",1,2,7),
("Month Of Sundays","Passenger","Flight of the Crow","Indie Folk",7,2,7),
("Things That Stop You Dreaming","Passenger","All the Little Lights","Indie Folk",2,2,7),
("Keep On Walking","Passenger","All the Little Lights","Indie Folk",7,2,7),
("I Hate","Passenger","All the Little Lights","Indie Folk",4,1,7),
("All the Little Lights","Passenger","All the Little Lights","Indie Folk",3,6,7),
("Home","Passenger","Young as the Morning Old as the Sea","Indie Folk",2,2,7),
("I. The Worst Guys","Childish Gambino","Because The Internet","Rap",6,6,9),
("IV. Sweatpants","Childish Gambino","Because The Internet","Rap",8,8,9),
("3005","Childish Gambino","Because The Internet", "Rap",9,8,9),
("All Night","Chance The Rapper","Coloring Book","Rap",9,9,7),
("Heartless","Kanye West","808s & Heartbreak","Rap",3,6,10),
("Love Lockdown","Kanye West","808s & Heartbreak","Rap",2,4,10),
("Party In the U.S.A","Miley Cyrus","The Time of Our Lives","Pop",8,9,10),
("Blank Space","Taylor Swift","1989","Pop",5,7,10),
("Style","Taylor Swift","1989","Pop",6,5,10),
("All You Had To Do Was Stay","Taylor Swift","1989","Pop",3,6,10),
("Wildest Dreams","Taylor Swift","1989","Pop",3,5,10),
("September","Earth,Wind,&Fire","The Eternal Dance","Disco",8,10,6),
("Dream Of Mickey Mantle","Bleachers","Gone Now","Indie Pop",4,8,1),
("Goodmorning","Bleachers","Gone Now","Indie Pop",3,5,1),
("Hate That You Know Me","Bleachers","Gone Now","Indie Pop",3,8,1),
("Don't Take The Money","Bleachers","Gone Now","Indie Pop",3,7,1),
("Everybody Lost Somebody","Bleachers","Gone Now","Indie Pop",1,5,1),
("All My Heros","Bleachers","Gone Now","Indie Pop",2,3,1),
("Goodbye","Bleachers","Gone Now","Indie Pop",3,6,1),
("I Miss Those Days","Bleachers","Gone Now","Indie Pop",5,6,1),
("Foreign Girls","Bleachers","Gone Now","Indie Pop",4,7,1),
("When We Were Young","Passenger","Young as the Morning Old as the Sea","Indie Folk",5,3,7),
("Green Light","Lorde","Melodrama","Pop",3,8,10),
("Sober","Lorde","Melodrama","Pop",5,9,10),
("Homemade Dynamite","Lorde","Melodrama","Pop",6,9,10),
("The Louvre","Lorde","Melodrama","Pop",7,3,10),
("Liability","Lorde","Melodrama","Pop",1,1,10),
("Hard Feelings/Loveless","Lorde","Melodrama","Pop",2,4,10),
("Sober II (Melodrama)","Lorde","Melodrama","Pop",3,6,10),
("Writer In The Dark","Lorde","Melodrama","Pop",1,3,10),
("Supercut","Lorde","Melodrama","Pop",6,9,10),
("Call Me Up","HOMESHAKE","Fresh Air","Indie Pop",7,3,0.8),
("Not U","HOMESHAKE","Fresh Air","Indie Pop",2,3,0.8),
("Boyish","Japanese Breakfast","Soft Sounds from Another Planet","Indie Pop",1,3,0.5),
("Till Death","Japanese Breakfast","Soft Sounds from Another Planet","Indie Pop",6,3,0.5);
