INSERT INTO Genres (genre)
VALUES
("pop"),
("dance pop"),
("pop rap"),
("rap"),
("rock"),
("modern rock"),
("trap music"),
("hip hop"),
("latin"),
("edm"),
("r&b"),
("pop rock"),
("alt rock"),
("classic rock"),
("alt metal"),
("latin pop"),
("indie rock"),
("indie pop"),
("soft rock"),
("viral pop"),
("indie r&b"),
("reggaeton"),
("folk pop"),
("pop punk"),
("tropical"),
("indie folk"),
("permanent wave"),
("electro house");

INSERT INTO Artists (name)
VALUES
("Still Woozy"),
("Father John Misty"),
("Ed Sheeran"),
("Phantogram"),
("Bleachers"),
("Miniature Tigers"),
("Aerosmith"),
("Sufjan Stevens"),
("Twin Peaks"),
("Frank Ocean"),
("Post Malone"),
("Yo La Tengo"),
("Beach House"),
("Japanese Breakfast"),
("Florist"),
("Bu","ha Trixie"),
("M83"),
("This Will Destroy You"),
("Little Joy"),
("Blood Orange"),
("Alvvays"),
("Wallows"),
("Tame Impala"),
("Nirvana"),
("Mild High Club"),
("slenderbodies"),
("fun."),
("Lorde"),
("Radiohead"),
("Cyberbully Mom Club"),
("The xx"),
("Phil Collins"),
("Joy Division"),
("Artic Monkeys"),
("Bon Iver"),
("HOMESHAKE"),
("Post Animal"),
("Beck"),
("The Smiths"),
("Oasis"),
("Earth, Wind & Fire"),
("Yeah Yeah Yeahs"),
("Weezer"),
("The Walters"),
("Unkown Mortal Orchastra"),
("Tears For Fears"),
("Talking Heads"),
("The Strokes"),
("The Shins"),
("Sampha"),
("The Postal Service"),
("Modest Mouse"),
("Mac Demarco"),
("The Kooks"),
("The Killers"),
("Kevin Morby"),
("Glass Animals"),
("Empire of the Sun");

INSERT INTO Songs (name, artist)
VALUES
("Clay Pigeons","Michael Cera"),
("The Suburbs", "Arcade Fire"),
("Such Great Heights","The Postal Services"),
("Yes I'm Changing","Tame Impalas"),
("Why'd You Only Call Me When You're High","Arctic Monkeys"),
("Pure Comedy","Father John Misty"),
("Leaving LA", "Father John Misty"),
("Burning Down The House","Talking Heads"),
("Fool","Frankie Cosmos"),
("Steady","Strongboys"),
("Nights","Frank Oceans"),
("Maps","Yeah Yeah Yeas"),
("Say It Ain't So","Weezers"),
("Buddy Holly","Weezers"),
("Weekend Woman","Weezers"),
("I Love You So","The Walters"),
("Pleaser","Wallows"),
("Uncomfortable","Wallows"),
("Feels Like We Only Go Backwards","Tame Impala"),
("The Less I Know The Better","Tame Impala");
